version: 0.1

phases:
  install:
    commands:
      - echo Entering install phase...
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Entering pre_build phase...
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - mvn -f pom.xml compile war:exploded
  post_build:
    commands:
      - echo Entering post_build phase...
      - echo Build completed on `date`
artifacts:
  files:
    - 'target/productsrvapp/WEB-INF/classes/com/product/config/WebConfig.class'
    - 'target/productsrvapp/WEB-INF/classes/com/product/controller/SampleController.class'
    - 'target/productsrvapp/WEB-INF/classes/com/product/controller/ProductController.class'
    - 'target/productsrvapp/WEB-INF/classes/com/product/dto/ProductDTO.class'
    - 'target/productsrvapp/WEB-INF/lib/commons-logging-1.2.jar'
    - 'target/productsrvapp/WEB-INF/lib/jackson-annotations-2.5.0.jar'
    - 'target/productsrvapp/WEB-INF/lib/jackson-core-2.5.0.jar'
    - 'target/productsrvapp/WEB-INF/lib/jackson-databind-2.5.0.jar'
    - 'target/productsrvapp/WEB-INF/lib/spring-aop-4.3.7.RELEASE.jar'
    - 'target/productsrvapp/WEB-INF/lib/spring-beans-4.3.7.RELEASE.jar'
    - 'target/productsrvapp/WEB-INF/lib/spring-context-4.3.7.RELEASE.jar'
    - 'target/productsrvapp/WEB-INF/lib/spring-core-4.3.7.RELEASE.jar'
    - 'target/productsrvapp/WEB-INF/lib/spring-expression-4.3.7.RELEASE.jar'
    - 'target/productsrvapp/WEB-INF/lib/spring-web-4.3.7.RELEASE.jar'
    - 'target/productsrvapp/WEB-INF/lib/spring-webmvc-4.3.7.RELEASE.jar'
    - 'target/productsrvapp/WEB-INF/sample-servlet.xml'
    - 'target/productsrvapp/WEB-INF/web.xml'
    - 'target/productsrvapp/index.html'
    - 'target/productsrvapp/appspec.yml'
    - 'target/productsrvapp/META-INF/MANIFEST.MF'
discard-paths: yes
